#!/usr/bin/env python3

# Dustin Marchak
# CSCI 5180 - Midterm Lab
# NMgithub.py - Create a GitHub repo, push SNMP output files, and sync modified files.

# imports
import os
import glob
import requests
from git import Repo

# Function Definitions

def get_credentials():
    # Prompt the user for their GitHub username and personal access token.
    username = input("GitHub username: ").strip()
    token = input("GitHub personal access token: ").strip()
    return username, token


def create_github_repo(username, token, repo_name):
    # Create a new repository on GitHub using the REST API.
    # Returns the HTTPS clone URL with the token embedded for authentication.

    print(f"\nCreating GitHub repository '{repo_name}'...")

    response = requests.post(
        "https://api.github.com/user/repos",
        headers={
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json",
        },
        json={
            "name": repo_name,
            "private": False,
            "description": "CSCI 5180 Midterm Lab - SNMP Network Management",
        },
    )

    if response.status_code == 201:
        print(f"  Repository '{repo_name}' created successfully.")
    elif response.status_code == 422:
        print(f"  Repository '{repo_name}' already exists, using existing repo.")
    else:
        print(f"  Error creating repo: {response.status_code} - {response.json().get('message', '')}")
        return None

    # Build the authenticated HTTPS URL for pushing
    remote_url = f"https://{username}:{token}@github.com/{username}/{repo_name}.git"
    return remote_url


def init_local_repo(repo_dir):
    # Initialize a local Git repository if one doesn't already exist.

    if os.path.isdir(os.path.join(repo_dir, ".git")):
        print("  Local git repo already initialized.")
        return Repo(repo_dir)

    print("  Initializing local git repository...")
    repo = Repo.init(repo_dir)
    return repo


def push_snmp_output(repo, remote_url):
    # Stage and push the .txt and .jpg files generated by NMsnmp.py to GitHub.

    print("\nPushing SNMP output files (.txt, .jpg) to GitHub...")
    repo_dir = repo.working_dir

    # Find all .txt and .jpg files in the repo directory
    txt_files = glob.glob(os.path.join(repo_dir, "*.txt"))
    jpg_files = glob.glob(os.path.join(repo_dir, "*.jpg"))
    output_files = txt_files + jpg_files

    if not output_files:
        print("  No .txt or .jpg files found to push.")
        return

    # Stage the output files
    for filepath in output_files:
        filename = os.path.basename(filepath)
        repo.index.add([filename])
        print(f"  Staged: {filename}")

    # Commit the staged files
    repo.index.commit("Add SNMP query results and CPU utilization graph")
    print("  Committed SNMP output files.")

    # Set up the remote and push
    if "origin" not in [r.name for r in repo.remotes]:
        repo.create_remote("origin", remote_url)
    else:
        repo.remotes.origin.set_url(remote_url)

    repo.remotes.origin.push(refspec="HEAD:refs/heads/main")
    print("  Pushed to GitHub.")


def push_modified_files(repo):
    # Compare the local repository against GitHub and push any modified files.

    print("\nChecking for modified files...")

    # Fetch the latest state from GitHub
    repo.remotes.origin.fetch()

    # Get list of changed files (staged, unstaged, and untracked)
    changed_files = []

    # Check for modified tracked files (unstaged changes)
    for item in repo.index.diff(None):
        changed_files.append(item.a_path)

    # Check for staged but uncommitted changes
    for item in repo.index.diff("HEAD"):
        changed_files.append(item.a_path)

    # Check for untracked files
    changed_files.extend(repo.untracked_files)

    # Remove duplicates
    changed_files = list(set(changed_files))

    if not changed_files:
        print("  No modified files found. Repository is up to date.")
        return

    # Stage all modified and untracked files
    print(f"  Found {len(changed_files)} modified/new file(s):")
    for filepath in sorted(changed_files):
        print(f"    {filepath}")
        repo.index.add([filepath])

    # Commit and push
    repo.index.commit("Update modified files")
    repo.remotes.origin.push(refspec="HEAD:refs/heads/main")
    print("  Pushed modified files to GitHub.")


def main():
    # Working directory is the Lab 5 folder
    repo_dir = os.path.dirname(os.path.abspath(__file__))
    repo_name = "CSCI5180-Midterm"

    # Step 1: Get GitHub credentials
    username, token = get_credentials()

    # Step 2: Create the GitHub repository
    remote_url = create_github_repo(username, token, repo_name)
    if not remote_url:
        return

    # Step 3: Initialize local git repo
    repo = init_local_repo(repo_dir)

    # Step 4: Push SNMP output files (.txt, .jpg) to GitHub
    push_snmp_output(repo, remote_url)

    # Step 5: Push any modified files (compare local vs GitHub)
    push_modified_files(repo)

    print(f"\nDone. Repository: https://github.com/{username}/{repo_name}")


# namespace check
if __name__ == "__main__":
    main()
